/*
 * This file is generated by jOOQ.
 */
package database.entities;


import database.entities.tables.Files;
import database.entities.tables.Kunden;
import database.entities.tables.Rechtsanwälte;
import database.entities.tables.records.FilesRecord;
import database.entities.tables.records.KundenRecord;
import database.entities.tables.records.RechtsanwälteRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<FilesRecord, Long> IDENTITY_FILES = Identities0.IDENTITY_FILES;
    public static final Identity<RechtsanwälteRecord, Long> IDENTITY_RECHTSANWÄLTE = Identities0.IDENTITY_RECHTSANWÄLTE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FilesRecord> FILES_PKEY = UniqueKeys0.FILES_PKEY;
    public static final UniqueKey<KundenRecord> KUNDEN_PKEY = UniqueKeys0.KUNDEN_PKEY;
    public static final UniqueKey<RechtsanwälteRecord> RECHTSANWÄLTE_PKEY = UniqueKeys0.RECHTSANWÄLTE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<FilesRecord, Long> IDENTITY_FILES = Internal.createIdentity(Files.FILES, Files.FILES.ID);
        public static Identity<RechtsanwälteRecord, Long> IDENTITY_RECHTSANWÄLTE = Internal.createIdentity(Rechtsanwälte.RECHTSANWÄLTE, Rechtsanwälte.RECHTSANWÄLTE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FilesRecord> FILES_PKEY = Internal.createUniqueKey(Files.FILES, "files_pkey", new TableField[] { Files.FILES.ID }, true);
        public static final UniqueKey<KundenRecord> KUNDEN_PKEY = Internal.createUniqueKey(Kunden.KUNDEN, "kunden_pkey", new TableField[] { Kunden.KUNDEN.ID }, true);
        public static final UniqueKey<RechtsanwälteRecord> RECHTSANWÄLTE_PKEY = Internal.createUniqueKey(Rechtsanwälte.RECHTSANWÄLTE, "rechtsanwälte_pkey", new TableField[] { Rechtsanwälte.RECHTSANWÄLTE.ID }, true);
    }
}
