/*
 * This file is generated by jOOQ.
 */
package database.entities;


import database.entities.tables.Files;
import database.entities.tables.Kunden;
import database.entities.tables.Rechtsanwälte;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1402752312;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.files</code>.
     */
    public final Files FILES = Files.FILES;

    /**
     * The table <code>public.kunden</code>.
     */
    public final Kunden KUNDEN = Kunden.KUNDEN;

    /**
     * The table <code>public.rechtsanwälte</code>.
     */
    public final Rechtsanwälte RECHTSANWÄLTE = Rechtsanwälte.RECHTSANWÄLTE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HIBERNATE_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Files.FILES,
            Kunden.KUNDEN,
            Rechtsanwälte.RECHTSANWÄLTE);
    }
}
