/*
 * This file is generated by jOOQ.
 */
package database.entities;


import database.entities.tables.Files;
import database.entities.tables.Kunden;
import database.entities.tables.Rechtsanwälte;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.files</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>public.kunden</code>.
     */
    public static final Kunden KUNDEN = Kunden.KUNDEN;

    /**
     * The table <code>public.rechtsanwälte</code>.
     */
    public static final Rechtsanwälte RECHTSANWÄLTE = Rechtsanwälte.RECHTSANWÄLTE;
}
