/*
 * This file is generated by jOOQ.
 */
package database.entities.tables.records;


import database.entities.tables.Kunden;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KundenRecord extends UpdatableRecordImpl<KundenRecord> implements Record9<Long, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 192718920;

    /**
     * Setter for <code>public.kunden.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.kunden.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.kunden.gender</code>.
     */
    public void setGender(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.kunden.gender</code>.
     */
    public String getGender() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.kunden.firstname</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.kunden.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.kunden.familyname</code>.
     */
    public void setFamilyname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.kunden.familyname</code>.
     */
    public String getFamilyname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.kunden.street</code>.
     */
    public void setStreet(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.kunden.street</code>.
     */
    public String getStreet() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.kunden.zip</code>.
     */
    public void setZip(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.kunden.zip</code>.
     */
    public String getZip() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.kunden.city</code>.
     */
    public void setCity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.kunden.city</code>.
     */
    public String getCity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.kunden.telnum</code>.
     */
    public void setTelnum(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.kunden.telnum</code>.
     */
    public String getTelnum() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.kunden.mail</code>.
     */
    public void setMail(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.kunden.mail</code>.
     */
    public String getMail() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Kunden.KUNDEN.ID;
    }

    @Override
    public Field<String> field2() {
        return Kunden.KUNDEN.GENDER;
    }

    @Override
    public Field<String> field3() {
        return Kunden.KUNDEN.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return Kunden.KUNDEN.FAMILYNAME;
    }

    @Override
    public Field<String> field5() {
        return Kunden.KUNDEN.STREET;
    }

    @Override
    public Field<String> field6() {
        return Kunden.KUNDEN.ZIP;
    }

    @Override
    public Field<String> field7() {
        return Kunden.KUNDEN.CITY;
    }

    @Override
    public Field<String> field8() {
        return Kunden.KUNDEN.TELNUM;
    }

    @Override
    public Field<String> field9() {
        return Kunden.KUNDEN.MAIL;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGender();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getFamilyname();
    }

    @Override
    public String component5() {
        return getStreet();
    }

    @Override
    public String component6() {
        return getZip();
    }

    @Override
    public String component7() {
        return getCity();
    }

    @Override
    public String component8() {
        return getTelnum();
    }

    @Override
    public String component9() {
        return getMail();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGender();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getFamilyname();
    }

    @Override
    public String value5() {
        return getStreet();
    }

    @Override
    public String value6() {
        return getZip();
    }

    @Override
    public String value7() {
        return getCity();
    }

    @Override
    public String value8() {
        return getTelnum();
    }

    @Override
    public String value9() {
        return getMail();
    }

    @Override
    public KundenRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public KundenRecord value2(String value) {
        setGender(value);
        return this;
    }

    @Override
    public KundenRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public KundenRecord value4(String value) {
        setFamilyname(value);
        return this;
    }

    @Override
    public KundenRecord value5(String value) {
        setStreet(value);
        return this;
    }

    @Override
    public KundenRecord value6(String value) {
        setZip(value);
        return this;
    }

    @Override
    public KundenRecord value7(String value) {
        setCity(value);
        return this;
    }

    @Override
    public KundenRecord value8(String value) {
        setTelnum(value);
        return this;
    }

    @Override
    public KundenRecord value9(String value) {
        setMail(value);
        return this;
    }

    @Override
    public KundenRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KundenRecord
     */
    public KundenRecord() {
        super(Kunden.KUNDEN);
    }

    /**
     * Create a detached, initialised KundenRecord
     */
    public KundenRecord(Long id, String gender, String firstname, String familyname, String street, String zip, String city, String telnum, String mail) {
        super(Kunden.KUNDEN);

        set(0, id);
        set(1, gender);
        set(2, firstname);
        set(3, familyname);
        set(4, street);
        set(5, zip);
        set(6, city);
        set(7, telnum);
        set(8, mail);
    }
}
