/*
 * This file is generated by jOOQ.
 */
package database.entities.tables.records;


import database.entities.tables.Rechtsanwälte;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RechtsanwälteRecord extends UpdatableRecordImpl<RechtsanwälteRecord> implements Record6<Long, String, String, String, String, String> {

    private static final long serialVersionUID = 519689854;

    /**
     * Setter for <code>public.rechtsanwälte.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.rechtsanwälte.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.rechtsanwälte.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.rechtsanwälte.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.rechtsanwälte.street</code>.
     */
    public void setStreet(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.rechtsanwälte.street</code>.
     */
    public String getStreet() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.rechtsanwälte.zip</code>.
     */
    public void setZip(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.rechtsanwälte.zip</code>.
     */
    public String getZip() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.rechtsanwälte.city</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.rechtsanwälte.city</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.rechtsanwälte.tag</code>.
     */
    public void setTag(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.rechtsanwälte.tag</code>.
     */
    public String getTag() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Rechtsanwälte.RECHTSANWÄLTE.ID;
    }

    @Override
    public Field<String> field2() {
        return Rechtsanwälte.RECHTSANWÄLTE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Rechtsanwälte.RECHTSANWÄLTE.STREET;
    }

    @Override
    public Field<String> field4() {
        return Rechtsanwälte.RECHTSANWÄLTE.ZIP;
    }

    @Override
    public Field<String> field5() {
        return Rechtsanwälte.RECHTSANWÄLTE.CITY;
    }

    @Override
    public Field<String> field6() {
        return Rechtsanwälte.RECHTSANWÄLTE.TAG;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getStreet();
    }

    @Override
    public String component4() {
        return getZip();
    }

    @Override
    public String component5() {
        return getCity();
    }

    @Override
    public String component6() {
        return getTag();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getStreet();
    }

    @Override
    public String value4() {
        return getZip();
    }

    @Override
    public String value5() {
        return getCity();
    }

    @Override
    public String value6() {
        return getTag();
    }

    @Override
    public RechtsanwälteRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RechtsanwälteRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RechtsanwälteRecord value3(String value) {
        setStreet(value);
        return this;
    }

    @Override
    public RechtsanwälteRecord value4(String value) {
        setZip(value);
        return this;
    }

    @Override
    public RechtsanwälteRecord value5(String value) {
        setCity(value);
        return this;
    }

    @Override
    public RechtsanwälteRecord value6(String value) {
        setTag(value);
        return this;
    }

    @Override
    public RechtsanwälteRecord values(Long value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RechtsanwälteRecord
     */
    public RechtsanwälteRecord() {
        super(Rechtsanwälte.RECHTSANWÄLTE);
    }

    /**
     * Create a detached, initialised RechtsanwälteRecord
     */
    public RechtsanwälteRecord(Long id, String name, String street, String zip, String city, String tag) {
        super(Rechtsanwälte.RECHTSANWÄLTE);

        set(0, id);
        set(1, name);
        set(2, street);
        set(3, zip);
        set(4, city);
        set(5, tag);
    }
}
